#!/bin/bash
#
# Title:      Valheim
# Author(s):  timekills
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    # CORE (MANDATORY) DO NOT CHANGE ###########################################

    - name: 'Set Known Facts'
      set_fact:
        pgrole: 'valheim'
        intport: '2456'
        extport: '2456'
        image: 'mbround18/valheim:latest'
        
    - name: 'Including cron job'
      include_tasks: '/opt/communityapps/apps/_core.yml'

    # EXTRA FUNCTIONS REQUIRED BY THE ROLE #####################################

    # LABELS #### KEEPS BOTTOM CLEAN ###########################################
    - name: 'Adding Traefik'
      set_fact:
        pg_labels:
          traefik.frontend.auth.forward.address: '{{gauth}}'
          traefik.enable: 'true'
          traefik.port: '{{intport}}'
          traefik.frontend.rule: 'Host:{{pgrole}}.{{domain.stdout}}{{tldset}}{{cname}}'

    - name: 'Setting PG Volumes'
      set_fact:
        pg_volumes:
          - '/opt/appdata/{{pgrole}}/valheim/saves:/valheim/saves'
          - '/opt/appdata/{{pgrole}}/valheim/server:/valheim/server'
          - '/etc/localtime:/etc/localtime:ro'

    - name: 'Setting PG ENV'
      set_fact:
        pg_env:

    # MAIN SCRIPT ##############################################################

    - name: 'Deploying {{pgrole}}'
      docker_container:
        name: '{{pgrole}}'
        image: '{{image}}'
        pull: yes
        published_ports:
          - '{{ports.stdout}}{{extport}}:{{intport}}'
          - '2456:2456/tcp'
          - '2456:2456/udp'
          - '2457:2457/tcp'
          - '2457:2457/udp'
          - '2458:2458/tcp'
          - '2458:2458/udp'
        volumes: '{{pg_volumes}}'
        env: '{{pg_env}}'
        restart_policy: unless-stopped
        networks:
          - name: plexguide
            aliases:
              - '{{pgrole}}'
        state: started
        labels: '{{pg_labels}}'

##PG-Community

##PG-Community
